### ISSUE TITLE
Dark mode incomplete for wide view layout

### ISSUE THREAD

**Issue by sync-coding** [fastaddons/Darko#15]
**Describe the bug**  
When the layout is set to be wide view, the dark mode is not complete. 
Oddly if I switch to classic view and switch back, it works fine. 

**Steps To Reproduce**  
1. Set layout to wide view.
2. Close Thunderbird completely and open it again.

**Expected behavior**  
All columns in dark mode.

**Device info:**
 - operating system: Win 10
 - Browser and version: Thunderbird 78.11.0 (64bit)
 - addon version: 2.0

**Comment by fastaddons** [comment]
Hello,
This is probably related to this Thunderbird bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1707573

You see, the code that handles the dark mode is extremely simple with almost no room for errors - there are no layouts, views, or anything related to Thunderbird. It just calls one function `browser.messageDisplayScripts.register()` and the dark mode CSS will be loaded everywhere all the time.

But the bug seems to be a bit random, you can try the other addon for dark mode, maybe it will work:
https://addons.thunderbird.net/thunderbird/addon/darkreader/

**Comment by sync-coding** [comment]
Thanks  for the reply. It is indeed a bit random. 
I regard it as solved since it does not really affect the use.

> 
> 
> Hello,
> This is probably related to this Thunderbird bug:
> https://bugzilla.mozilla.org/show_bug.cgi?id=1707573
> 
> You see, the code that handles the dark mode is extremely simple with almost no room for errors - there are no layouts, views, or anything related to Thunderbird. It just calls one function `browser.messageDisplayScripts.register()` and the dark mode CSS will be loaded everywhere all the time.
> 
> But the bug seems to be a bit random, you can try the other addon for dark mode, maybe it will work:
> https://addons.thunderbird.net/thunderbird/addon/darkreader/
