### ISSUE TITLE
Is this abandoned? Can you open the source so I can make some updates if so?

### ISSUE THREAD

**Issue by RickKukiela** [fastaddons/Darko#19]
So this plugin is doing what I want but its not working correctly with images (Its washing them out for some reason):

![image](https://user-images.githubusercontent.com/3813238/156631539-7c2e1355-ed59-4d60-9ffa-7f5d98717f89.png)

Issues in this tracker are not being responded to and no updates have been made to the addon in quite some time. I would like to grab the source to see if I can resolve the issue if you're too busy or otherwise unable or unwilling to continue working on it.

EDIT: I see you have responded to another issue recently so I guess you're still around. The issue I commented on several months ago (https://github.com/fastaddons/Darko/issues/9) was never responded to so I assumed no one was working on this project anymore.

Thanks

**Comment by RickKukiela** [comment]
Also, I have the invert image color option disabled in the settings so it really shouldn't be modifying the images at all, right? 
![image](https://user-images.githubusercontent.com/3813238/156632580-3559223b-f223-4945-85eb-b81b2e91f885.png)

**Comment by fastaddons** [comment]
Hello Rick,
Not abandoned, I'm just too busy with my other addons so things are going slowly here.
The "dark mode theory" is much more complicated than I first though so many things doesn't work well.
For example if image is "applied" using a CSS "background" property, it will be inverted because I can't think of CSS selector that would skip such element. In the case of those social icons, those may be SVG elements, maybe I can should exclude SVG...

Anyway, in the end, I think a custom CSS file with exceptions and special cases needs to be build that would handle these and many others.

And lastly, why are you not using the "[Dark Reader](https://addons.thunderbird.net/en-US/thunderbird/addon/darkreader/)" addon? :)
It's already open source and it works much better (it hurts me to say that).

**Comment by RickKukiela** [comment]
@fastaddons I understand the work load issue for sure. Thank you for recommending the other extension I honestly did not know about it and was under the impression this was the only extension that does this for some reason. That one is working good for me in this regard.

The images in question for me on your extension were not background images. Your app was washing out the images of ALL the images in the emails that I received, just so you know.

Thanks again.
