### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by wvxwxvw** [fastaddons/Darko#20]
Why such a large number of fonts? The profile backup has swollen by 1.6MB, maybe can do without them for Windows?  
  
In general, I removed fonts and links to them. The add-on has slimmed down to 384Kb. Everything seems to be working. Why are they needed there? :)

**Comment by fastaddons** [comment]
Yeah, it's crazy huge. It's the Google Roboto font which is part of the [Vuetify library ](https://vuetifyjs.com/)I use for the Options page.
I use Vuetify in most of my addons because it's nice looking, it has many great UI components and it's easy to use (it even has dark mode built in). The only downside is that it's huge and a bit slow to load.

However, the big size shouldn't be a problem in this case. The font and the whole library is loaded only when you open Options page for my addon, so it won't be loaded into email window nor in background script, so this won't affect performance at all.

**Comment by wvxwxvw** [comment]
That’s not what I’m talking about. He’s inflating the size of backups, which I have a lot of. Just, if I leave them in each extension, then under the backups of Mozilla products will have to hold a separate disk.
  
In general, it’s not that important, for myself I try to delete them everywhere, including in Firefox. There I also have almost daily backups. The authors would do a mini version of this.   
  
The thread can be closed if you wish.

**Comment by fastaddons** [comment]
Why having many backups and not keep only last few?
Anyway, I can't really fix this. The font is part of the library so it has to be used and loading it dynamically from web is forbidden (addons have to have bundled all resources).

**Comment by wvxwxvw** [comment]
@fastaddons 
Throw in fonts that weigh five times as much as the extension itself, it's not rational. But ultimately I don't care, for myself I'll be removing them. And the addon is great, thank you.
