### ISSUE TITLE
Don't invert if background is already black

### ISSUE THREAD

**Issue by liurui39660** [fastaddons/Darko#6]
**Describe the bug**  
I received an email, whose background color is already black, but Darko still inverts it, so the background becomes white.

**Steps To Reproduce**  
1. Receive an email whose background is black color
1. Turn on Darko

**Expected behavior**  
The background is not inverted and remains black

**Actual behavior**
The background is white

**Device info:**
 - OS: Windows 10
 - Thunderbird:  78.4.3 (64-bit)
 - Addon version: 2.0 (Nov 15, 2020)

**Comment by fastaddons** [comment]
Thanks for reporting. I will look into this.
But it's not always this simple. Sometimes the outer background is dark but the box with the text in the middle is white. And that case it still makes sense to invert it so that you read white text on dark background surrounded by white outer background.

One other approach would be to make a screenshot and simply count how many pixels is dark / white and do the inversion based on that.
Another "hotfix" is using some rules to exclude certain senders from inversion:
https://github.com/fastaddons/Darko/issues/2
Most emails is white, so those that are already dark are usually from some specific senders, like newsletters. Right?

**Comment by liurui39660** [comment]
I don't think making a screenshot is a good idea, one thing is the unseen part of the email body may cause some unexpected issues, also this may cause some privacy issue (some users are always sensitive about it). 

And, yes, most emails are white, but the point here is not to show emails in black, it's to show them in black automatically. Adding rules manually is only a temporary workaround, this may not be a good solution for the majority of users, especially when they have multiple machines running Thunderbirds.

**Comment by fastaddons** [comment]
I've just checked and it seems that the captureTab API is not available in Thunderbird so screenshots are not possible.
I will try to make some good dark email simply by analyzing text/background styles.

Regarding privacy - you really have nothing to worry about, this addon doesn't have any "host" permissions so even if it wold collect some data, it would never be able to send it anywhere. So you are safe.

One thing that would help me here is a collection of dark emails, so that I have some test samples where I could verify the functionality.
So if you have a non-private dark email, please forward it to my support email with some "Dark email example" heading. Thanks!

**Comment by liurui39660** [comment]
I found some emails from two senders, GitKraken and Steam. One example from each sender is sent to your admin mailbox. Interestingly, the one from Steam is very close to the type you mentioned earlier: Background is black, background of background is white.

**Comment by fastaddons** [comment]
Thanks! Feel free to send me more if you find more. I will try to look at this during the weekend (or next week). 
Currently I need to finish one bigger upgrade for my group speed dial addon.

**Comment by fastaddons** [comment]
Hello,
Just to let you know. I'm very busy with my other addons so I don't see this coming any time soon.
**Also, it hurts me to say but there is now a new addon for Thunderbird call "[Dark Reader](https://addons.thunderbird.net/thunderbird/addon/darkreader/)" which seems to be even better than mine.**
It's also a popular addon for Firefox and his author has much more experience with "dark features" then I do.

**Comment by liurui39660** [comment]
Thanks, so far the features provided in your plugin are already enough, I'll try Dark Reader if more advanced features are required.
