### ISSUE TITLE
Some images have inverted colors!

### ISSUE THREAD

**Issue by fastaddons** [fastaddons/Darko#9]
By default, images should not be inverted (image nodes "img").
However sometimes image is "hidden" in a style, for example in a "div" node:
```
<div style="background-image: url(https://secure.meetupstatic.com/photos/event/a/c/1/e/600_493604062.jpeg)"></div>
```
I'm not sure though if this can be fixed...

**Comment by RickKukiela** [comment]
I was just coming here to report this. In my email signature I have my company logo as a background image so that my <a> tag can sit on top of it and make better use of the space. I have already outlined the image in white so that it looks good in both dark and light mode. See:

![email-sig-2021](https://user-images.githubusercontent.com/3813238/142056917-ed8b1ba7-0b66-47d6-a120-de79db91808c.png)

I do not want this image inverted: 

![image](https://user-images.githubusercontent.com/3813238/142057048-efddfd9e-c437-4bf5-9fd0-9ee3fafdb7b9.png)

**Comment by RickKukiela** [comment]
I just realized this bug is a year old and has not been resolved. I also noticed this is not a code repo. Is there a code repo where I can do PR to fix this for you? I'd really like to get this fixed. Thanks.

**Comment by mherrmann3** [comment]
Those cases could be captured with the following CSS selector:
```css
  /* Also undo inversion for background images */
  [style*="background-image:"], [background*="."] {
    filter: invert(100%) hue-rotate(180deg) !important;
  }
```

(see https://github.com/fastaddons/Darko/issues/8#issuecomment-1327748181)

The `[background*="."]` captures cases where a `<body>` or `<td>` element has a background attribute, which points to an image.

**Comment by fastaddons** [comment]
Amazing job finding this selector!
I'll include it in the next release (hopefully sometime this week).
I have to say, this is the first time I see there is a "background" attribute... although I can't find any docs for that.

**Comment by mherrmann3** [comment]
The `background` attribute is ancient (before the times of CSS) and deprecated/discouraged in HTML5 in favor of using CSS's background property, but it's "documented":
* https://html.com/attributes/td-background/
* https://html.com/attributes/body-background/

I only added it because I got a mail this week that used it 🤷🏻‍♂️

**Comment by fastaddons** [comment]
Done, new version 3.5 has been released with updated CSS that re-inverts the background images. So far it seems to be working fine:
```js
const filterStyle = `filter: invert(100%) hue-rotate(${HUE_ROTATE}) !important;`;
const CSS_CODE = `@media not print {
body:not(.no-darko) {
  ${filterStyle}
  background: ${FIREFOX_BACKGROUND} !important;
}
body:not(.no-darko) :is(img, [style*="background-image:"], [background*="."], g-emoji) {
  ${filterStyle}
}
html[style*="color-scheme"] {
  color-scheme: light !important;
}
}`;
```
I've added also "g-emoji" selector which fixes emoji used in Github emails. Sadly those unicode can't be fixed with just CSS.
Thanks again for helping me with this :)
